app:
  main:
    host: 0.0.0.0
    port: 8080
    use_graph_ql: True
  url:
    tlg: https://api.telegram.org/bot1970336189:AAGgyNk995DtkqunTE6fVtUHzNBo_G4D51M/sendMessage
  auth:
    url: https://smapi.pv-api.sbc.space/ds-7043743249627480066/graphql
    key: 21fbb619dece43deb1c80b3280a54f6c
    secret: 94a2d93bfb7a4cb4bfcc4bf31b1f37a1
  token_map:
    sberauto: 1970336189:AAGgyNk995DtkqunTE6fVtUHzNBo_G4D51M